name: Release them all BWUAHAHAHAH
on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'debug'
        required: true
        default: 'false'
        type: choice
        options:
          - false
          - true

jobs:
  get_build_date:
    runs-on: ubuntu-latest
    outputs:
      build_datedash: ${{ steps.set_date.outputs.datedash }}
      build_date: ${{ steps.set_date.outputs.date }}
    steps:
      - name: Set build date
        id: set_date
        run:  |
          export datenow=$(TZ=America/New_York date +%Y-%m-%d-%H%M%S)
          echo "datedash=$(echo $datenow)" >> $GITHUB_OUTPUT
          echo "date=$(echo $datenow | sed 's|\-||g')" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    needs: get_build_date

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: actions/checkout@v4

      - name: Install Exfat
        run: sudo apt -y install exfatprogs

      - name: Build img (andr36oid only)
        run: |
          export BuildImgEnv=github
          export GH_build_date=${{ needs.get_build_date.outputs.build_date }}
          export NewOSList="andr36oid"
          echo "Building only: $NewOSList"
          chmod a+x ./buildimg.sh
          export ghdebug=${{ inputs.debug }}
          ./buildimg.sh $NewOSList
          df -h /
          sleep $(shuf -i 1-100 -n 1)

      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files: R36S-Multiboot-*.img.xz.7z.*
          draft: true
          name: batch ${{ needs.get_build_date.outputs.build_datedash }}
          tag_name: v${{ needs.get_build_date.outputs.build_date }}
          body: |
            # [Download Images Here](https://${{ github.repository_owner }}.github.io/R36S-Multiboot/)
            (https://${{ github.repository_owner }}.github.io/R36S-Multiboot)

      - name: Sleep before retry
        if: failure() && steps.release.outcome == 'failure'
        run: |
          sleep $(( $(shuf -i 30-300 -n 1) ))

      - name: Release Retry
        id: retry1
        if: failure() && steps.release.outcome == 'failure'
        uses: softprops/action-gh-release@v2
        with:
          files: R36S-Multiboot-*.img.xz.7z.*
          draft: true
          name: batch ${{ needs.get_build_date.outputs.build_datedash }}
          tag_name: v${{ needs.get_build_date.outputs.build_date }}
          body: |
            # [Download Images Here](https://${{ github.repository_owner }}.github.io/R36S-Multiboot/)
            (https://${{ github.repository_owner }}.github.io/R36S-Multiboot)

      - name: Sleep before retry 2
        if: failure() && steps.retry1.outcome == 'failure'
        run: |
          sleep $(( $(shuf -i 30-300 -n 1) ))

      - name: Release Retry 2
        id: retry2
        if: failure() && steps.retry1.outcome == 'failure'
        uses: softprops/action-gh-release@v2
        with:
          files: R36S-Multiboot-*.img.xz.7z.*
          draft: true
          name: batch ${{ needs.get_build_date.outputs.build_datedash }}
          tag_name: v${{ needs.get_build_date.outputs.build_date }}
          body: |
            # [Download Images Here](https://${{ github.repository_owner }}.github.io/R36S-Multiboot/)
            (https://${{ github.repository_owner }}.github.io/R36S-Multiboot)

      - name: Sleep before retry 3
        if: failure() && steps.retry2.outcome == 'failure'
        run: |
          sleep $(( $(shuf -i 30-300 -n 1) ))

      - name: Release Retry 3
        id: retry3
        if: failure() && steps.retry2.outcome == 'failure'
        uses: softprops/action-gh-release@v2
        with:
          files: R36S-Multiboot-*.img.xz.7z.*
          draft: true
          name: batch ${{ needs.get_build_date.outputs.build_datedash }}
          tag_name: v${{ needs.get_build_date.outputs.build_date }}
          body: |
            # [Download Images Here](https://${{ github.repository_owner }}.github.io/R36S-Multiboot/)
            (https://${{ github.repository_owner }}.github.io/R36S-Multiboot)
